### ISSUE TITLE
Disabling link preview makes bot messages empty

### ISSUE THREAD

**Issue by Genda1ph** [aliasfalse/genesis#64]
Hello, I've stumbled upon a bug today

I hated these bloated link preview messages in chat, so I disabled them in options, under Text & images -> Link preview.

About two weeks later I learned that I don't see contents of Genesis' messages at all. After poking around in options, I found out that this the aforementioned option breaks messages from the bot.

Reproduction: disable Link preview in Options, trigger any bot message

Here are quick reproduction screenshots http://imgur.com/a/htOjV

Tested on: Windows, Linux, Android.

**Comment by aliasfalse** [comment]
Known, can't and won't change at the present time. If a setting for both is produced in the future, it'll be reconsidered. It's a discord thing. the embeds are more structurable and compact than either code blocks or any other format.
